[package]
name = "myexample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icrate = { version = "0.1.0", path = "../crates/icrate", features = ["Foundation", "Foundation_all"] }
